# Site settings
title: HTML5 Barebone Test Page for Barebook
email: acamarian66@gmail.com
description: 
baseurl: ""
url: "" # the base hostname & protocol for your site


# Collections
collections:
  elements:
    output: false

# Front Matter Defaults

# General settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
sass:
  sass_dir: public/styles/sass
  style: :compressed